# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ADE9000_form.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.setEnabled(True)
        Form.resize(700, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(700, 600))
        Form.setMaximumSize(QtCore.QSize(700, 600))
        self.lcd_Voltage = QtWidgets.QLCDNumber(Form)
        self.lcd_Voltage.setGeometry(QtCore.QRect(50, 50, 121, 41))
        self.lcd_Voltage.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_Voltage.setObjectName("lcd_Voltage")
        self.label_Vrms = QtWidgets.QLabel(Form)
        self.label_Vrms.setGeometry(QtCore.QRect(178, 56, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_Vrms.setFont(font)
        self.label_Vrms.setObjectName("label_Vrms")
        self.label_Arms = QtWidgets.QLabel(Form)
        self.label_Arms.setGeometry(QtCore.QRect(180, 106, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_Arms.setFont(font)
        self.label_Arms.setObjectName("label_Arms")
        self.lcd_Current = QtWidgets.QLCDNumber(Form)
        self.lcd_Current.setGeometry(QtCore.QRect(50, 100, 121, 41))
        self.lcd_Current.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_Current.setObjectName("lcd_Current")
        self.label_Voltage = QtWidgets.QLabel(Form)
        self.label_Voltage.setGeometry(QtCore.QRect(10, 50, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_Voltage.setFont(font)
        self.label_Voltage.setObjectName("label_Voltage")
        self.label_ADE9000 = QtWidgets.QLabel(Form)
        self.label_ADE9000.setGeometry(QtCore.QRect(10, 10, 681, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_ADE9000.setFont(font)
        self.label_ADE9000.setObjectName("label_ADE9000")
        self.lcd_Power = QtWidgets.QLCDNumber(Form)
        self.lcd_Power.setGeometry(QtCore.QRect(50, 150, 121, 41))
        self.lcd_Power.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_Power.setObjectName("lcd_Power")
        self.label_W = QtWidgets.QLabel(Form)
        self.label_W.setGeometry(QtCore.QRect(180, 156, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_W.setFont(font)
        self.label_W.setObjectName("label_W")
        self.label_Power = QtWidgets.QLabel(Form)
        self.label_Power.setGeometry(QtCore.QRect(10, 150, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_Power.setFont(font)
        self.label_Power.setTextFormat(QtCore.Qt.AutoText)
        self.label_Power.setObjectName("label_Power")
        self.label_Hz = QtWidgets.QLabel(Form)
        self.label_Hz.setGeometry(QtCore.QRect(448, 56, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_Hz.setFont(font)
        self.label_Hz.setObjectName("label_Hz")
        self.label_Freq = QtWidgets.QLabel(Form)
        self.label_Freq.setGeometry(QtCore.QRect(260, 50, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_Freq.setFont(font)
        self.label_Freq.setTextFormat(QtCore.Qt.AutoText)
        self.label_Freq.setObjectName("label_Freq")
        self.lcd_VTHD = QtWidgets.QLCDNumber(Form)
        self.lcd_VTHD.setGeometry(QtCore.QRect(320, 100, 121, 41))
        self.lcd_VTHD.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_VTHD.setObjectName("lcd_VTHD")
        self.lcd_ITHD = QtWidgets.QLCDNumber(Form)
        self.lcd_ITHD.setGeometry(QtCore.QRect(320, 150, 121, 41))
        self.lcd_ITHD.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_ITHD.setObjectName("lcd_ITHD")
        self.lcd_Freq = QtWidgets.QLCDNumber(Form)
        self.lcd_Freq.setGeometry(QtCore.QRect(320, 50, 121, 41))
        self.lcd_Freq.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_Freq.setObjectName("lcd_Freq")
        self.label_ITHD = QtWidgets.QLabel(Form)
        self.label_ITHD.setGeometry(QtCore.QRect(250, 150, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_ITHD.setFont(font)
        self.label_ITHD.setObjectName("label_ITHD")
        self.label_Percent1 = QtWidgets.QLabel(Form)
        self.label_Percent1.setGeometry(QtCore.QRect(450, 106, 21, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_Percent1.setFont(font)
        self.label_Percent1.setObjectName("label_Percent1")
        self.label_VHD = QtWidgets.QLabel(Form)
        self.label_VHD.setGeometry(QtCore.QRect(250, 100, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_VHD.setFont(font)
        self.label_VHD.setObjectName("label_VHD")
        self.label_Percent2 = QtWidgets.QLabel(Form)
        self.label_Percent2.setGeometry(QtCore.QRect(450, 156, 21, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_Percent2.setFont(font)
        self.label_Percent2.setObjectName("label_Percent2")
        self.label_degC = QtWidgets.QLabel(Form)
        self.label_degC.setGeometry(QtCore.QRect(670, 106, 21, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_degC.setFont(font)
        self.label_degC.setObjectName("label_degC")
        self.label_Percent3 = QtWidgets.QLabel(Form)
        self.label_Percent3.setGeometry(QtCore.QRect(668, 56, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_Percent3.setFont(font)
        self.label_Percent3.setObjectName("label_Percent3")
        self.lcd_PF = QtWidgets.QLCDNumber(Form)
        self.lcd_PF.setGeometry(QtCore.QRect(540, 50, 121, 41))
        self.lcd_PF.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_PF.setObjectName("lcd_PF")
        self.label_Temp = QtWidgets.QLabel(Form)
        self.label_Temp.setGeometry(QtCore.QRect(500, 100, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_Temp.setFont(font)
        self.label_Temp.setObjectName("label_Temp")
        self.label_PF = QtWidgets.QLabel(Form)
        self.label_PF.setGeometry(QtCore.QRect(500, 50, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_PF.setFont(font)
        self.label_PF.setObjectName("label_PF")
        self.lcd_Temp = QtWidgets.QLCDNumber(Form)
        self.lcd_Temp.setGeometry(QtCore.QRect(540, 100, 121, 41))
        self.lcd_Temp.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_Temp.setObjectName("lcd_Temp")
        self.label_Voltage_2 = QtWidgets.QLabel(Form)
        self.label_Voltage_2.setGeometry(QtCore.QRect(10, 100, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_Voltage_2.setFont(font)
        self.label_Voltage_2.setObjectName("label_Voltage_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "ADE9000 Monitor"))
        self.label_Vrms.setText(_translate("Form", "Vrms"))
        self.label_Arms.setText(_translate("Form", "Arms"))
        self.label_Voltage.setText(_translate("Form", "電圧"))
        self.label_ADE9000.setText(_translate("Form", "ADE9000 High Performance, Multiphase Energy, and Power Quality Monitoring IC"))
        self.label_W.setText(_translate("Form", "W"))
        self.label_Power.setText(_translate("Form", "電力"))
        self.label_Hz.setText(_translate("Form", "Hz"))
        self.label_Freq.setText(_translate("Form", "周波数"))
        self.label_ITHD.setText(_translate("Form", "電流THD"))
        self.label_Percent1.setText(_translate("Form", "%"))
        self.label_VHD.setText(_translate("Form", "電圧THD"))
        self.label_Percent2.setText(_translate("Form", "%"))
        self.label_degC.setText(_translate("Form", "℃"))
        self.label_Percent3.setText(_translate("Form", "%"))
        self.label_Temp.setText(_translate("Form", "温度"))
        self.label_PF.setText(_translate("Form", "力率"))
        self.label_Voltage_2.setText(_translate("Form", "電流"))

